export const API_ROUTES = {
  HEALTH: "health",
  AUTH: "auth",
  ME: "me",
  SIGN_UP: "sign-up",
  SIGN_IN: "sign-in",
  SIGN_OUT: "sign-out",
  SESSION: "session",
  CONTEXT: "context",
  CAMPUS: "campus",
  SELECT: "select",
  PUBLIC: "public",
  TENANT_BRANDING: "tenant-branding",
  TENANT_CONTEXT: "tenant-context",
  ONBOARDING: "onboarding",
  INSTITUTIONS: "institutions",
  COUNTS: "counts",
  CAMPUSES: "campuses",
  STUDENTS: "students",
  ACADEMIC_YEARS: "academic-years",
  EXAMS: "exams",
  TERMS: "terms",
  MARKS: "marks",
  CURRENT: "current",
  ARCHIVE: "archive",
  RESTORE: "restore",
  BRANDING: "branding",
} as const;
